WINDOW_NAME = "JUKEBOX PLAYBLAST"

MAYA_VIEWPORT_ATTS = [
    "nurbsCurves",
    "nurbsSurfaces",
    "cv",
    "hulls",
    "polymeshes",
    "subdivSurfaces",
    "planes",
    "lights",
    "cameras",
    "imagePlane",
    "joints",
    "ikHandles",
    "deformers",
    "dynamics",
    "particleInstancers",
    "fluids",
    "hairSystems",
    "follicles",
    "nCloths",
    "nParticles",
    "nRigids",
    "dynamicConstraints",
    "locators",
    "dimensions",
    "pivots",
    "handles",
    "textures",
    "strokes",
    "motionTrails",
    "pluginShapes",
    "clipGhosts",
    "greasePencils",
    "controllers",
]
